name: eight_app
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.8.3
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  firebase_ui_firestore: ^1.5.5
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.6
  go_router: ^9.0.3
  google_sign_in: ^6.1.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  modal_bottom_sheet: ^3.0.0-pre
  package_info_plus: ^4.0.2

flutter_launcher_icons: # dart pub run flutter_launcher_icons
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: assets/app/ic_launcher.png

flutter:
  uses-material-design: true

  assets:
    - assets/app/
    - assets/font/
    - assets/icon/
    - assets/image/

  fonts:
    - family: machine
      fonts:
        - asset: assets/font/type_machine.ttf
