name: eight_app
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_svg: ^2.0.7
  go_router: ^9.0.3
  package_info_plus: ^4.0.2

flutter_launcher_icons: # dart pub run flutter_launcher_icons
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: assets/app/ic_launcher.png

flutter:
  uses-material-design: true

  assets:
    - assets/app/
    - assets/font/
    - assets/icon/

  fonts:
    - family: nunito
      fonts:
        - asset: assets/font/nunito.ttf
