import 'package:eight_app/model/categoria_model.dart';
import 'package:eight_app/service/categoria_service.dart';

final List<CategoriaModel> listaCategoria = [
  CategoriaModel(
    idCategoria: CategoriaEnum.ALL.value,
    texto: 'todas',
    isDesabilitada: false,
    isSelecionar: false,
  ),
  CategoriaModel(
    idCategoria: CategoriaEnum.MY.value,
    texto: 'minhas',
    isDesabilitada: false,
    isSelecionar: false,
  ),
  CategoriaModel(
    idCategoria: CategoriaEnum.BOOKMARK.value,
    texto: 'favoritas',
    isDesabilitada: false,
    isSelecionar: false,
  ),
  CategoriaModel(
    idCategoria: CategoriaEnum.ANIMALS.value,
    texto: 'animais',
    isDesabilitada: false,
    isSelecionar: true,
  ),
  CategoriaModel(
    idCategoria: CategoriaEnum.ART.value,
    texto: 'arte',
    isDesabilitada: false,
    isSelecionar: true,
  ),
  CategoriaModel(
    idCategoria: CategoriaEnum.ASTROLOY.value,
    texto: 'astrologia',
    isDesabilitada: false,
    isSelecionar: true,
  ),
  CategoriaModel(
    idCategoria: CategoriaEnum.ASTRONOMY.value,
    texto: 'astronomia',
    isDesabilitada: false,
    isSelecionar: true,
  ),
  CategoriaModel(
    idCategoria: CategoriaEnum.DRINK.value,
    texto: 'bebida',
    isDesabilitada: false,
    isSelecionar: true,
  ),
  CategoriaModel(
    idCategoria: CategoriaEnum.BEAUTY.value,
    texto: 'beleza',
    isDesabilitada: false,
    isSelecionar: true,
  ),
  CategoriaModel(
    idCategoria: CategoriaEnum.SCIENCE.value,
    texto: 'ciências',
    isDesabilitada: false,
    isSelecionar: true,
  ),
  CategoriaModel(
    idCategoria: CategoriaEnum.CLIMATE_WEATHER.value,
    texto: 'clima e tempo',
    isDesabilitada: false,
    isSelecionar: true,
  ),
  CategoriaModel(
    idCategoria: CategoriaEnum.COMEDY.value,
    texto: 'comédia',
    isDesabilitada: false,
    isSelecionar: true,
  ),
  CategoriaModel(
    idCategoria: CategoriaEnum.FOOD.value,
    texto: 'comida',
    isDesabilitada: false,
    isSelecionar: true,
  ),
  CategoriaModel(
    idCategoria: CategoriaEnum.CULTURE.value,
    texto: 'cultura',
    isDesabilitada: false,
    isSelecionar: true,
  ),
  CategoriaModel(
    idCategoria: CategoriaEnum.MONEY.value,
    texto: 'dinheiro',
    isDesabilitada: false,
    isSelecionar: true,
  ),
  CategoriaModel(
    idCategoria: CategoriaEnum.ENTERTAINMENT.value,
    texto: 'entretenimento',
    isDesabilitada: false,
    isSelecionar: true,
  ),
  CategoriaModel(
    idCategoria: CategoriaEnum.SPORTS.value,
    texto: 'esportes',
    isDesabilitada: false,
    isSelecionar: true,
  ),
  CategoriaModel(
    idCategoria: CategoriaEnum.STUDIES.value,
    texto: 'estudos',
    isDesabilitada: false,
    isSelecionar: true,
  ),
  CategoriaModel(
    idCategoria: CategoriaEnum.EVENTS.value,
    texto: 'eventos',
    isDesabilitada: false,
    isSelecionar: true,
  ),
  CategoriaModel(
    idCategoria: CategoriaEnum.EXTRATERRESTRIAL.value,
    texto: 'extraterrestre',
    isDesabilitada: false,
    isSelecionar: true,
  ),
  CategoriaModel(
    idCategoria: CategoriaEnum.FAMILY.value,
    texto: 'família',
    isDesabilitada: false,
    isSelecionar: true,
  ),
  CategoriaModel(
    idCategoria: CategoriaEnum.FOLKLORE.value,
    texto: 'folclore',
    isDesabilitada: false,
    isSelecionar: true,
  ),
  CategoriaModel(
    idCategoria: CategoriaEnum.PHOTOGRAPHY_VIDEO.value,
    texto: 'fotografia e vídeos',
    isDesabilitada: false,
    isSelecionar: true,
  ),
  CategoriaModel(
    idCategoria: CategoriaEnum.GEOGRAPHY.value,
    texto: 'geografia',
    isDesabilitada: false,
    isSelecionar: true,
  ),
  CategoriaModel(
    idCategoria: CategoriaEnum.INTERNET.value,
    texto: 'internet',
    isDesabilitada: false,
    isSelecionar: true,
  ),
  CategoriaModel(
    idCategoria: CategoriaEnum.FASHION.value,
    texto: 'moda',
    isDesabilitada: false,
    isSelecionar: true,
  ),
  CategoriaModel(
    idCategoria: CategoriaEnum.MUSIC.value,
    texto: 'música',
    isDesabilitada: false,
    isSelecionar: true,
  ),
  CategoriaModel(
    idCategoria: CategoriaEnum.RELIGION.value,
    texto: 'religião',
    isDesabilitada: false,
    isSelecionar: true,
  ),
  CategoriaModel(
    idCategoria: CategoriaEnum.ROMANCE.value,
    texto: 'romance',
    isDesabilitada: false,
    isSelecionar: true,
  ),
  CategoriaModel(
    idCategoria: CategoriaEnum.HEALTH.value,
    texto: 'saúde',
    isDesabilitada: false,
    isSelecionar: true,
  ),
  CategoriaModel(
    idCategoria: CategoriaEnum.SEX.value,
    texto: 'sexo',
    isDesabilitada: false,
    isSelecionar: true,
  ),
  CategoriaModel(
    idCategoria: CategoriaEnum.TATTOO_PIERCING.value,
    texto: 'tatuagem e piercing',
    isDesabilitada: false,
    isSelecionar: true,
  ),
  CategoriaModel(
    idCategoria: CategoriaEnum.TECHNOLOGY.value,
    texto: 'tecnologia',
    isDesabilitada: false,
    isSelecionar: true,
  ),
  CategoriaModel(
    idCategoria: CategoriaEnum.HORROR.value,
    texto: 'terror',
    isDesabilitada: false,
    isSelecionar: true,
  ),
  CategoriaModel(
    idCategoria: CategoriaEnum.JOB.value,
    texto: 'trabalho',
    isDesabilitada: false,
    isSelecionar: true,
  ),
  CategoriaModel(
    idCategoria: CategoriaEnum.TRANSPORT.value,
    texto: 'transportes',
    isDesabilitada: false,
    isSelecionar: true,
  ),
  CategoriaModel(
    idCategoria: CategoriaEnum.TV_MOVIES_SERIES.value,
    texto: 'tv, filmes e séries',
    isDesabilitada: false,
    isSelecionar: true,
  ),
  CategoriaModel(
    idCategoria: CategoriaEnum.VEHICLES.value,
    texto: 'veículos',
    isDesabilitada: false,
    isSelecionar: true,
  ),
  CategoriaModel(
    idCategoria: CategoriaEnum.LIFE_DEATH.value,
    texto: 'vida e morte',
    isDesabilitada: false,
    isSelecionar: true,
  ),
  CategoriaModel(
    idCategoria: CategoriaEnum.VIOLENCE.value,
    texto: 'violência',
    isDesabilitada: false,
    isSelecionar: true,
  ),
  CategoriaModel(
    idCategoria: CategoriaEnum.SHAME.value,
    texto: 'vergonha',
    isDesabilitada: false,
    isSelecionar: true,
  )
];
